service: spikelist

provider:
  name: aws
  runtime: go1.x
  region: us-west-2

package:
 exclude:
   - ./**
 include:
   - ./spikelist

functions:
  GetRate:
    handler: spikelist
    environment:
      HANDLER_NAME: rate
    events:
      - http:
          method: get
          path: /rate
  GetRegister:
    handler: spikelist
    environment:
      HANDLER_NAME: register
    events:
      - http:
          method: get
          path: /register
  GetUpload:
    handler: spikelist
    environment:
      HANDLER_NAME: upload
    events:
      - http:
          method: get
          path: /upload

resources:
  Resources:
    Levels:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: levels
        AttributeDefinitions:
          - AttributeName: level_id
            AttributeType: S
          - AttributeName: level_maker
            AttributeType: S
        KeySchema:
          - AttributeName: level_id
            KeyType: HASH
          - AttributeName: level_maker
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    Nicknames:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: nicknames
        AttributeDefinitions:
          - AttributeName: nickname
            AttributeType: S
        KeySchema:
          - AttributeName: nickname
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST